In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from causal_optoconnectics.core import find_first_response_spike, find_response_spikes
import numpy as np

In [30]:
s = np.array([
    1, 
    2, 
    3, 
    4, 
    5])
a = np.array([
    .1, .99, # before 1 (Z False)
    1.11, 1.12, # after 1
    2, # before 2 (Z True)
    2.13, # after 2
    3.14, 3.15, # after 3
    3.999, # before 4 (Z True)
    4.16, # after 4
    5.17# before 1
])
c = np.array([
    .2, 
    1.13, 1.23, 
    2.34, 
    3.2, 
    4.1, 
    5.5])
find_response_spikes(a, c, s, dt=.3, dz=0.01)

(array([False,  True, False,  True, False]),
 [array([0.11, 0.12]),
  array([0.13]),
  array([0.14, 0.15]),
  array([0.16]),
  array([0.17])],
 [array([0.13, 0.23]),
  array([], dtype=float64),
  array([0.2]),
  array([0.1]),
  array([], dtype=float64)])

In [25]:
1-0.99

0.010000000000000009